### PR TITLE
fprintf(stderr) → BLOSC_TRACE_ERROR()

### LINKED ISSUE #471: Inconsistency: BLOSC_TRACE_ERROR / fprintf
**Describe the bug**

Is there a reason for using `fprintf` instead of `BLOSC_TRACE_ERROR` in [blosc/trunc-prec.c](https://github.com/Blosc/c-blosc2/blob/main/blosc/trunc-prec.c)?
https://github.com/Blosc/c-blosc2/blob/09b4e461db4f895812de3e651e31145825b17168/blosc/trunc-prec.c#L80-L82

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
Fixes #471.

Use BLOSC_TRACE_ERROR() everywhere under:
- `blosc`
- `include`
- `plugins` (except `*_test.c` files)
    
Use `fprintf(stderr)` everywhere under;
- `examples`
- `tests`
    
Of course, do not modify:
- `internal-complibs`

### CODE REVIEW

File: plugins/filters/ndmean/test_ndmean_mean.c [hunk 1]
```diff
@@ -77,7 +77,7 @@ static int test_ndmean(blosc2_schunk *schunk) {
   free(smeta);
 
   if (ndim != 1) {
-    fprintf(stderr, "This test only works for ndim = 1");
+    BLOSC_TRACE_ERROR("This test only works for ndim = 1");
```
Comment (FrancescAlted) [inline plugins/filters/ndmean/test_ndmean_mean.c:80]: This is a test, and I prefer the regular `printf`.  Can you remove this one?

**Comment by FrancescAlted** [comment]
Looks almost good.  Yes, you are right that examples and tests should not use `BLOSC_TRACE_ERROR` and a regular `printf` would be better.

File: plugins/filters/ndmean/test_ndmean_mean.c (hunk 1 above)
Comment (DimitriPapadopoulos) [reply plugins/filters/ndmean/test_ndmean_mean.c]: Done.

Together with `BLOSC_TRACE_ERROR()` everywhere in library code and `fprintf(stderr)` everywhere in examples and tests.

**Comment by FrancescAlted** [comment]
That's great @DimitriPapadopoulos !
